local_bakerry/bakerry/urls.py
from django.urls import path, include

app_name = "pages"


from . import views
urlpatterns =[
    # path("/", views.bakerry, name="bakerry"),
    path("home/", views.home, name="home"),
    path("about/", views.about, name="about"),
    path("menu/", views.menu, name="menu"),
    path("contact/", views.contact, name="contact"),
]

local_bakerry/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("bakerry/", include("bakerry.urls")),
]

local_bakerry/bakerry/models.py
from django.db import models

# Create your models here.

local_bakerry/bakerry/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render (request, "pages/home.html")

def about(request):
    return render (request, "pages/about.html")

def menu(request):
    return render (request, "pages/menu.html")

def contact(request):
    return render (request, "pages/contact.html")

#  return render (request, "authors/all_authors.html")

local_bakerry/templates/pages/about.html
{% extends "partials/base.html" %}

{% block title %} This is about us  {% endblock title %}
{% block body %}
<p>About Us</p>
{% endblock body %}

local_bakerry/templates/pages/contact.html
{% extends "partials/base.html" %}

{% block title %} Contact Us Here {% endblock title %}
{% block body %}
<p> our contacts</p>
<p> You can contact us via our email and number below. our contact servics are available 24/7 and we are always ready to serve you</p>
<h1> oluwajidesolomon123@gmail.com</h1>
<h1> 08134134406</h1>
{% endblock body %}

local_bakerry/templates/pages/home.html
{% extends "partials/base.html" %}

{% block title %} homepage {% endblock title %}
{% block body %}
<h1> Welcome to our homepage </h1>
<p> Here on this our home page, you can click the menu icon to explore our menu</p>
<p>We are always here to serve you and make your cravings come through</p>
<h2> Enjoy your meal @ OLAMI cravings</h2>
{% endblock body %}

local_bakerry/templates/pages/menu.html
{% extends "partials/base.html" %}

{% block title %} Our menu  {% endblock title %}
{% block body %}
<h1>Here you can explore our menu and get your cravings satisfied </h1>
<p> jollof and friedrice</p>
<p>semo and egusi</p>
<p>pounded yam and egusi</p>
<p>jollof rice alone</p>
<p>chinese rice</p>
<p>local rice </p>
<p>pepper soup</p>
<p>starch</p>
<p>ofada rice and sauce</p>
<p>rice and chicken stew</p>
{% endblock body %}

local_bakerry/templates/partials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}default title{% endblock title %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
    {% include "./header.html" %}

    {% block body %}
    
    {% endblock body %}
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

local_bakerry/templates/partials/header.html
<header>
        <nav>
            <ul>
                <li><a href="{% url 'pages:home' %}">Home</a></li>
                <li><a href="{% url 'pages:menu' %}">Menu</li>
                <li><a href="{% url 'pages:contact' %}">Contact</li>
                <li><a href="{% url 'pages:about' %}">About</li>
            </ul>
        </nav>
    </header>