lms/authors/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = "authors"

urlpatterns = [
    path("all-authors/", views.all_authors, name="all_authors"),
]

lms/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("library/", include("library.urls")),
    path("authors/", include("authors.urls")),
    path("", include("dtl.urls")),
    
]

lms/dtl/urls.py
from django.urls import path

from . import views

urlpatterns= [
    path("dtl/", views.example_dtl, name="dtl"),
    path("test-dtl/", views.test_dtl, name="test_dtl")
]

lms/library/urls.py
from django.urls import path


from . import views

app_name = "library"

urlpatterns = [
    path("home/", views.home, name="home"),
    path("book_list/", views.book_list, name="books"),
]

lms/authors/models.py
from django.db import models

# Create your models here.
class Author(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    date_of_birth = models.DateField()


    def __str__(self):
        return f"{self.first_name} {self.last_name}"

lms/dtl/models.py
from django.db import models

# Create your models here.

lms/library/models.py
from django.db import models

from authors.models import Author

# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    no_of_pages = models.PositiveIntegerField()
    published_on = models.DateField()

    def __str__(self):
        return f"{self.title} {self.author}"

lms/authors/views.py
from django.shortcuts import render

# Create your views here.
def all_authors(request):
    return render (request, "authors/all_authors.html")

lms/dtl/views.py
from django.shortcuts import render

# Create your views here.
def example_dtl(request):
   
    return render(request, "dtl/dtl.html")

def test_dtl(request):
    context = {
        "food": "rice",
        "ingredients": ["tomatoes", "salt", "pepper", "onions", "groundnut oil"],
        "is_favorite": True,
        "time_in_minutes": "30mins"
    }
    return render(request,"dtl/test-dtl.html", context)

lms/library/views.py
from django.shortcuts import render
# from authors.models import authors

# Create your views here.
def home(request):
    return render(request, "library/home.html")

def book_list(request):
    return render(request, "library/book_list.html")

lms/templates/authors/all_authors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Authors page</title>
</head>
<body>
    <h2> Welcome to Authors page</h2>
    <h4> Names of Authors</h4>
    <p> Emmanuel Precious </p>
    <p> Oluwajide Solomon</p>
    <p> Fadiya Gabriel </p>
    <a href="{% url 'library:home' %}">Library Home</a>
</body>
</html>

lms/templates/dtl/dtl.html
>   {% extends "partials/base.html" %}
    {% block title %}
    my home page
    {% endblock title %}

    {% block body %}
    
    <h1>My name is Solomon</h1>
    <h4> I like to eat rice</h4>
    {% endblock body %}

lms/templates/dtl/test-dtl.html
    {% extends "partials/base.html" %}
    {% block title %}
    test DTL
    {% endblock title %}
    
    {% block body %}
    <h1>The food i will be cooking is {{ food }}</h1>
    <h4>the ingredients to cook {{food}} are</h4>
    <ul>
    {% for ingredient in ingredients  %}
    <li>{{ ingredient }}</li>
    {% endfor %}
    </ul>
    {% if is_favorite %}
    <p>rice is my favorite</p>
    {% else %}
    <p> Rice is not my favorite</p>
    {% endif %}
    <p>it takes {{ time_in_minutes }} to cook {{ food }}</p>
    {% endblock body %}

lms/templates/library/book_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>books</title>
</head>
<body>
    <h4> These are the books available</h4>
</body>
</html>

lms/templates/library/home.html
    <title>home page</title>
</head>
<body>
    <h3> welcome to homepage</h3>
    <a href="{% url 'authors:all_authors' %}">All Authors</a>
</body>
</html>

lms/templates/partials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Default Title{% endblock title %} </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    
     {% block body %}
    
    {% endblock body %}
</body>
</html>

lms/templates/partials/header.html
<header>
    <nav>
         <li><a href="{% url 'pages:home' %}"></a>Home</li>
         <li><a href="{% url 'pages:about' %}">About</li>
         <li><a href="{% url 'pages:contact' %}">Contact</li>
        <li><a href="{% url 'pages:login' %}">login</li>
    </nav>
    </header>